name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.9.0
  drift: ^2.29.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.2
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.41
  window_manager: ^0.5.1
  uuid: ^4.5.2
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  drift_dev: ^2.29.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
