name = "espanol-pro-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
# Environment variables go here

[[d1_databases]]
binding = "DB"
database_name = "espanol-pro-db"
database_id = "b82f1c79-87d8-4414-8204-30d9c282339e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "espanol-pro-content"

[ai]
binding = "AI"
